apiVersion: v1
kind: Service
metadata:
  name: api-key-management-service
spec:
  selector:
    app: api-key-management-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
