apiVersion: v1
kind: Service
metadata:
  name: api-key-management-service-loadbalancer
spec:
  selector:
    app: api-key-management-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer
