apiVersion: apps/v1
kind: Deployment
metadata:
  name: wilayah-ri-fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wilayah-ri-fe
  template:
    metadata:
      labels:
        app: wilayah-ri-fe
    spec:
      containers:
        - name: wilayah-ri-fe
          image: hakimamarullah/wilayah-ri-fe:beta
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "256m"
              memory: "256Mi"
            limits:
              cpu: "512m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 10
            failureThreshold: 6
      automountServiceAccountToken: false
