apiVersion: v1
kind: Service
metadata:
  name: wilayah-service-loadbalancer
spec:
  selector:
    app: wilayah-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: ClusterIP
