apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 1  # Adjust based on your needs
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
        env:  # Corrected indentation
        - name: RABBITMQ_DEFAULT_USER
          value: micro
        - name: RABBITMQ_DEFAULT_PASS
          value: micro
      volumes:  # Corrected indentation
      - name: rabbitmq-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
