apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1  # Adjust based on your traffic needs and replication requirements
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16  # Use a stable version
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_DB
          value: micro
        - name: POSTGRES_USER
          value: micro
        - name: POSTGRES_PASSWORD
          value: micro
      volumes:  # Corrected indentation
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc